# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dis.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_latitude = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_latitude.setDecimals(5)
        self.doubleSpinBox_latitude.setMinimum(-90.0)
        self.doubleSpinBox_latitude.setMaximum(90.0)
        self.doubleSpinBox_latitude.setProperty("value", 0.0)
        self.doubleSpinBox_latitude.setObjectName("doubleSpinBox_latitude")
        self.gridLayout.addWidget(self.doubleSpinBox_latitude, 0, 3, 1, 1)
        self.pushButton_load_image = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_load_image.setObjectName("pushButton_load_image")
        self.gridLayout.addWidget(self.pushButton_load_image, 1, 0, 1, 6)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.doubleSpinBox_longitude = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_longitude.setDecimals(5)
        self.doubleSpinBox_longitude.setMinimum(-180.0)
        self.doubleSpinBox_longitude.setMaximum(180.0)
        self.doubleSpinBox_longitude.setObjectName("doubleSpinBox_longitude")
        self.gridLayout.addWidget(self.doubleSpinBox_longitude, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.spinBox_zoom = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_zoom.setMaximum(17)
        self.spinBox_zoom.setObjectName("spinBox_zoom")
        self.gridLayout.addWidget(self.spinBox_zoom, 0, 5, 1, 1)
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.gridLayout.addWidget(self.label_image, 2, 0, 1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_load_image.setText(_translate("MainWindow", "Загрузить картинку"))
        self.label_2.setText(_translate("MainWindow", "Широта"))
        self.label.setText(_translate("MainWindow", "Долгота"))
        self.label_3.setText(_translate("MainWindow", "Маштаб"))
        self.label_image.setText(_translate("MainWindow", "Image"))
